import { NextResponse } from 'next/server';
import { db } from '@/lib/db';

export const runtime = 'edge';

interface GeneratedContent {
    summary: string;
    tiktok: {
        hook: string;
        body: string;
        cta: string;
    };
    xThread: string[];
    linkedin: string;
    note: string;
    watermark: boolean;
}

/**
 * Mock content generation (will be replaced with real LLM API)
 */
async function generateContent(url: string, isPro: boolean): Promise<GeneratedContent> {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // Extract domain for mock personalization
    let domain = 'unknown';
    try {
        domain = new URL(url).hostname;
    } catch {
        // Invalid URL, use default
    }

    return {
        summary: `📌 **Core Insight from ${domain}**\n\nThis content discusses the key principles of [Topic]. The main takeaway is that success comes from consistent execution and understanding your audience's needs.\n\n**Key Points:**\n1. Start with the problem, not the solution\n2. Iterate based on real feedback\n3. Focus on value delivery over virality`,
        tiktok: {
            hook: "90% of creators waste their content...",
            body: "Here's how the top 1% repurpose a single piece into a week's worth of posts. Step 1: Extract the core message. Step 2: Adapt the format to each platform. Step 3: Schedule strategically.",
            cta: "Follow for more content hacks. Link in bio for the full system.",
        },
        xThread: [
            "🧵 I analyzed the content at " + domain + " and found 3 patterns that drive engagement:\n\n(Thread 1/5)",
            "1/ **The Hook**: Every piece starts with a pattern interrupt. They don't say 'Hello' - they say 'You're doing X wrong.'\n\n(2/5)",
            "2/ **The Value Stack**: They give away the 'what' for free, sell the 'how'. This builds trust AND demand.\n\n(3/5)",
            "3/ **The Loop**: Every ending creates a new beginning. 'Now that you know X, the question is Y...'\n\n(4/5)",
            "TL;DR: Content that converts = Hook + Value + Loop.\n\nWant this done for you automatically? Try OneSource.\n\n(5/5)",
        ],
        linkedin: `I spent 2 hours analyzing ${domain} so you don't have to.\n\nHere's what I learned:\n\nThe best content creators don't create more - they repurpose smarter.\n\nThey take ONE piece of gold and turn it into:\n→ 5 X posts\n→ 3 LinkedIn articles\n→ 2 TikTok scripts\n→ 1 Newsletter\n\nThis isn't working harder. It's working strategically.\n\nThe question isn't "what should I post today?"\n\nIt's "how can I maximize what I've already created?"\n\nAgree? ♻️ Repost to help others.`,
        note: `# ${domain} から学んだコンテンツ戦略\n\nこの記事では、${domain}のコンテンツ戦略を分析し、そこから得られた3つの重要なインサイトを共有します。\n\n## 1. フック（引き込み）の技術\n最初の3秒で読者の注意を引くことが重要です。\n\n## 2. 価値提供の階層化\n無料で「何を」を伝え、有料で「どうやって」を売る。\n\n## 3. ループ構造\n終わりは次の始まり。常に続きを匂わせる。\n\n---\n\n${isPro ? '' : '\\n\\n*Generated by OneSource - onesource.app*'}`,
        watermark: !isPro,
    };
}

export async function POST(request: Request) {
    try {
        const body = await request.json();
        const { url, userId } = body;

        if (!url) {
            return NextResponse.json(
                { error: 'URL is required' },
                { status: 400 }
            );
        }

        // Validate URL format
        try {
            new URL(url);
        } catch {
            return NextResponse.json(
                { error: 'Invalid URL format' },
                { status: 400 }
            );
        }

        // Check if user can generate
        const canGenResult = await db.canGenerate(userId || null);

        if (!canGenResult.allowed) {
            return NextResponse.json(
                {
                    error: canGenResult.reason,
                    upgradeRequired: true
                },
                { status: 403 }
            );
        }

        // Determine if user is Pro
        let isPro = false;
        if (userId) {
            const user = await db.getUserById(userId);
            isPro = user?.plan === 'pro';
        }

        // Generate content
        const content = await generateContent(url, isPro);

        // Record usage
        await db.recordUsage(userId || null, url);

        return NextResponse.json({
            success: true,
            content,
            remainingFree: isPro ? null : (canGenResult.remainingFree ?? 0) - 1,
        });
    } catch (error) {
        console.error('Generate error:', error);
        return NextResponse.json(
            { error: 'Failed to generate content' },
            { status: 500 }
        );
    }
}
