"use client";

import React from 'react';

interface GeneratedContent {
    summary: string;
    tiktok: { hook: string; body: string; cta: string };
    xThread: string[];
    linkedin: string;
    note: string;
    watermark: boolean;
}

const Card = ({ children, style, copyText }: { children: React.ReactNode, style?: React.CSSProperties, copyText?: string }) => {
    const [copied, setCopied] = React.useState(false);

    const handleCopy = async () => {
        if (copyText) {
            await navigator.clipboard.writeText(copyText);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    return (
        <div
            style={{
                background: "var(--glass-surface)",
                border: "1px solid var(--glass-border)",
                borderRadius: "24px",
                padding: "1.5rem",
                backdropFilter: "blur(12px)",
                color: "#fff",
                overflow: "hidden",
                position: "relative",
                boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
                transition: "transform 0.2s ease, border-color 0.2s ease",
                cursor: copyText ? "pointer" : "default",
                ...style
            }}
            onClick={handleCopy}
            onMouseEnter={(e) => {
                e.currentTarget.style.transform = "translateY(-5px)";
                e.currentTarget.style.borderColor = "rgba(168, 85, 247, 0.4)";
            }}
            onMouseLeave={(e) => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.borderColor = "var(--glass-border)";
            }}
        >
            {copyText && (
                <div style={{
                    position: "absolute",
                    top: "0.75rem",
                    right: "0.75rem",
                    fontSize: "0.7rem",
                    background: copied ? "#22c55e" : "rgba(255,255,255,0.1)",
                    padding: "4px 8px",
                    borderRadius: "6px",
                    color: copied ? "white" : "#a1a1aa"
                }}>
                    {copied ? "Copied!" : "Click to copy"}
                </div>
            )}
            {children}
        </div>
    );
};

interface BentoGridProps {
    content?: GeneratedContent;
}

export default function BentoGrid({ content }: BentoGridProps) {
    // Default placeholder content
    const summary = content?.summary || `📌 **Core Insight**

This area will display the distilled essence of your content.

Whether it's a 1-hour YouTube video or a 5,000-word blog post, our AI extracts the "Gold" — the key insights that drive engagement.`;

    const tiktok = content?.tiktok || {
        hook: "You are wasting 90% of your content...",
        body: "Here is how to fix it using AI. One click, 5 formats.",
        cta: "Link in bio for early access."
    };

    const xThread = content?.xThread || [
        "1/5 The secret to scaling content isn't working harder. It's smart repurposing. 🧵👇",
        "2/5 Take your best blog post. Break it down into 3 key points.",
        "3/5 Turn point #1 into a visual hook."
    ];

    const linkedin = content?.linkedin || `"Efficiency is the key to scaling your personal brand in 2026.
Today I want to share a framework that helped me save 20 hours a week..."`;

    return (
        <div style={{
            display: "grid",
            gridTemplateColumns: "repeat(4, 1fr)",
            gridTemplateRows: "repeat(3, 240px)",
            gap: "1.5rem",
            maxWidth: "1200px",
            width: "100%",
            margin: "2rem auto",
            padding: "0 1rem"
        }}>
            {/* 1. Summary / Main Content - Large Top Left */}
            <Card
                style={{ gridColumn: "span 2", gridRow: "span 2", background: "linear-gradient(135deg, rgba(255,255,255,0.03) 0%, rgba(255,255,255,0.01) 100%)" }}
                copyText={summary}
            >
                <h3 style={{ fontSize: "1.5rem", marginBottom: "1rem", color: "#a855f7", fontWeight: "bold" }}>✨ Core Concept</h3>
                <p style={{ color: "#d1d5db", lineHeight: "1.6", fontSize: "1rem", whiteSpace: "pre-wrap" }}>
                    {summary}
                </p>
                {content?.watermark && (
                    <p style={{ position: "absolute", bottom: "1rem", right: "1rem", fontSize: "0.7rem", color: "#52525b" }}>
                        Generated by OneSource
                    </p>
                )}
            </Card>

            {/* 2. TikTok Script - Vertical */}
            <Card
                style={{ gridColumn: "span 1", gridRow: "span 2", position: "relative", overflow: "hidden" }}
                copyText={content?.watermark ? undefined : `Hook: ${tiktok.hook}\n\nBody: ${tiktok.body}\n\nCTA: ${tiktok.cta}`}
            >
                {content?.watermark && (
                    <div style={{
                        position: "absolute",
                        top: 0, left: 0, right: 0, bottom: 0,
                        background: "rgba(0,0,0,0.6)",
                        backdropFilter: "blur(8px)",
                        zIndex: 10,
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        justifyContent: "center",
                        textAlign: "center"
                    }}>
                        <span style={{ fontSize: "2rem", marginBottom: "0.5rem" }}>🔒</span>
                        <h4 style={{ fontWeight: "bold", marginBottom: "0.5rem" }}>Pro Feature</h4>
                        <p style={{ fontSize: "0.8rem", color: "#d1d5db" }}>Upgrade to unlock TikTok scripts</p>
                    </div>
                )}
                <div style={{ display: "flex", alignItems: "center", marginBottom: "1rem" }}>
                    <span style={{ fontSize: "1.5rem", marginRight: "0.5rem" }}>🎵</span>
                    <h3 style={{ fontSize: "1.2rem", color: "#fff", fontWeight: "bold" }}>TikTok</h3>
                </div>
                <div style={{ fontSize: "0.9rem", color: "#e5e7eb", lineHeight: "1.5", opacity: content?.watermark ? 0.3 : 1 }}>
                    <p style={{ marginBottom: "0.5rem" }}><strong style={{ color: "#ec4899" }}>Hook (0-3s):</strong> <br />"{tiktok.hook}"</p>
                    <p style={{ marginBottom: "0.5rem" }}><strong style={{ color: "#ec4899" }}>Body:</strong> <br />{tiktok.body}</p>
                    <p><strong style={{ color: "#ec4899" }}>CTA:</strong> <br />{tiktok.cta}</p>
                </div>
            </Card>

            {/* 3. X Thread - Vertical */}
            <Card
                style={{ gridColumn: "span 1", gridRow: "span 3" }}
                copyText={xThread.join("\n\n")}
            >
                <div style={{ display: "flex", alignItems: "center", marginBottom: "1rem" }}>
                    <span style={{ fontSize: "1.5rem", marginRight: "0.5rem" }}>🐦</span>
                    <h3 style={{ fontSize: "1.2rem", color: "#fff", fontWeight: "bold" }}>X Thread</h3>
                </div>
                <div style={{ fontSize: "0.9rem", color: "#e5e7eb", lineHeight: "1.5", overflow: "auto", maxHeight: "calc(100% - 3rem)" }}>
                    {xThread.map((tweet, i) => (
                        <p key={i} style={{ borderBottom: "1px solid rgba(255,255,255,0.1)", paddingBottom: "0.5rem", marginBottom: "0.5rem" }}>
                            <strong>@you</strong><br />
                            {tweet}
                        </p>
                    ))}
                </div>
            </Card>

            {/* 4. LinkedIn - Horizontal */}
            <Card
                style={{ gridColumn: "span 3", gridRow: "span 1" }}
                copyText={linkedin}
            >
                <div style={{ display: "flex", alignItems: "center", marginBottom: "1rem" }}>
                    <span style={{ fontSize: "1.5rem", marginRight: "0.5rem" }}>💼</span>
                    <h3 style={{ fontSize: "1.2rem", color: "#fff", fontWeight: "bold" }}>LinkedIn Post</h3>
                </div>
                <p style={{ color: "#d1d5db", fontSize: "1rem", lineHeight: "1.6", whiteSpace: "pre-wrap" }}>
                    {linkedin}
                </p>
            </Card>

            {/* 5. Note.com - Full Width */}
            <Card
                style={{ gridColumn: "span 4", gridRow: "span 1", position: "relative", overflow: "hidden" }}
                copyText={content?.watermark ? undefined : content?.note}
            >
                {content?.watermark && (
                    <div style={{
                        position: "absolute",
                        top: 0, left: 0, right: 0, bottom: 0,
                        background: "rgba(0,0,0,0.6)",
                        backdropFilter: "blur(8px)",
                        zIndex: 10,
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        justifyContent: "center",
                        textAlign: "center"
                    }}>
                        <span style={{ fontSize: "2rem", marginBottom: "0.5rem" }}>🔒</span>
                        <h4 style={{ fontWeight: "bold", marginBottom: "0.5rem" }}>Pro Feature</h4>
                        <p style={{ fontSize: "0.8rem", color: "#d1d5db" }}>Upgrade to unlock Note.com articles</p>
                    </div>
                )}
                <div style={{ display: "flex", alignItems: "center", marginBottom: "1rem" }}>
                    <span style={{ fontSize: "1.5rem", marginRight: "0.5rem" }}>📝</span>
                    <h3 style={{ fontSize: "1.2rem", color: "#fff", fontWeight: "bold" }}>Note.com Article</h3>
                </div>
                <p style={{ color: "#d1d5db", fontSize: "1rem", lineHeight: "1.6", whiteSpace: "pre-wrap", opacity: content?.watermark ? 0.3 : 1 }}>
                    {content?.note || "Note content..."}
                </p>
            </Card>
        </div>
    );
}
